# Spring Web Poort binnen de container (Spring Boot standaard is 8080)
server.port=8083

# Postgres Configuratie (Let op: de host is 'postgres', niet 'localhost'!)
spring.datasource.url=jdbc:postgresql://localhost:5455/ballcom_ordering
spring.datasource.username=ball_admin
spring.datasource.password=supersecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always

# RabbitMQ Configuratie (Let op: de host is 'rabbitmq'!)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=ball_admin
spring.rabbitmq.password=supersecretpassword

# Zorg dat Spring Boot niet crasht als de DB er een fractie van een seconde later is
spring.datasource.hikari.initialization-fail-timeout=0