services:

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: ballcom-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ball_admin
      RABBITMQ_DEFAULT_PASS: supersecretpassword

  postgres-ordering:
    image: postgres:16
    container_name: postgres-ordering
    environment:
      POSTGRES_DB: ordering_db
      POSTGRES_USER: ball_admin
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5455:5432"
    volumes:
      - ordering_postgres_data:/var/lib/postgresql/data
      - ./init-scripts/ordering:/docker-entrypoint-initdb.d

  postgres-payment:
    image: postgres:16
    container_name: postgres-payment
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: ball_admin
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5456:5432"
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data
      - ./init-scripts/payment:/docker-entrypoint-initdb.d

  postgres-shipment:
    image: postgres:16
    container_name: postgres-shipment
    environment:
      POSTGRES_DB: shipment_db
      POSTGRES_USER: ball_admin
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5457:5432"
    volumes:
      - shipment_postgres_data:/var/lib/postgresql/data
      - ./init-scripts/shipment:/docker-entrypoint-initdb.d

  postgres-catalog:
    image: postgres:16
    container_name: postgres-catalog
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: ball_admin
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5458:5432"
    volumes:
      - catalog_postgres_data:/var/lib/postgresql/data
      - ./init-scripts/catalog:/docker-entrypoint-initdb.d

  postgres-customer:
    image: postgres:16
    container_name: postgres-customer
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: ball_admin
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5459:5432"
    volumes:
      - customer_postgres_data:/var/lib/postgresql/data
      - ./init-scripts/customer:/docker-entrypoint-initdb.d


  ordering-service:
    build: ./ballcom-ordering
    container_name: ordering-service
    ports:
      - "8082:8080"
    depends_on:
      - postgres-ordering
      - rabbitmq

  payment-service:
    build: ./ballcom-payment
    container_name: payment-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres-payment
      - rabbitmq

  customer-service:
    build: ./ballcom-customer
    container_name: customer-service
    ports:
      - "8083:8080"
    depends_on:
      - postgres-customer
      - rabbitmq

  shipment-service:
    build: ./ballcom-shipment
    container_name: shipment-service
    ports:
      - "8084:8080"
    depends_on:
      - postgres-shipment
      - rabbitmq

  catalog-service:
    build: ./ballcom-catalog
    container_name: catalog-service
    ports:
      - "8085:8080"
    depends_on:
      - postgres-catalog
      - rabbitmq

  gateway-service:
    build: ./ballcom-gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - ordering-service
      - payment-service
      - customer-service
      - shipment-service
      - catalog-service
volumes:
  ordering_postgres_data:
  payment_postgres_data:
  shipment_postgres_data:
  catalog_postgres_data:
  customer_postgres_data: