services:
  postgres-ordering:
    image: postgres:16
    container_name: postgres-ordering
    environment:
      POSTGRES_DB: ordering_db
      POSTGRES_USER: ball_admin
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5455:5432"
    volumes:
      - ordering_postgres_data:/var/lib/postgresql/data
      - ./init-scripts/ordering:/docker-entrypoint-initdb.d

  postgres-payment:
    image: postgres:16
    container_name: postgres-payment
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: ball_admin
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5456:5432"
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data
      - ./init-scripts/payment:/docker-entrypoint-initdb.d

  postgres-shipment:
    image: postgres:16
    container_name: postgres-shipment
    environment:
      POSTGRES_DB: shipment_db
      POSTGRES_USER: ball_admin
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5457:5432"
    volumes:
      - shipment_postgres_data:/var/lib/postgresql/data
      - ./init-scripts/shipment:/docker-entrypoint-initdb.d

  postgres-catalog:
    image: postgres:16
    container_name: postgres-catalog
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: ball_admin
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5458:5432"
    volumes:
      - catalog_postgres_data:/var/lib/postgresql/data
      - ./init-scripts/catalog:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: ballcom-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ball_admin
      RABBITMQ_DEFAULT_PASS: supersecretpassword

volumes:
  ordering_postgres_data:
  payment_postgres_data:
  shipment_postgres_data:
  catalog_postgres_data: