server.port=8083

spring.datasource.url=jdbc:postgresql://postgres-customer:5432/customer_db
spring.datasource.username=ball_admin
spring.datasource.password=supersecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=ball_admin
spring.rabbitmq.password=supersecretpassword

spring.datasource.hikari.initialization-fail-timeout=0