package com.ballcom.shared.events;

public enum EventType {
    ORDER_PLACED,
    CUSTOMER_REGISTERED, 
    PAYMENT_INITIATED, 
    PAYMENT_COMPLETED, 
    PAYMENT_FAILED, 
    PAYMENT_AWAITING_DELIVERY, 
    ORDER_PICKED, 
    PACKAGE_SHIPPED, 
    PACKAGE_DELIVERED
}
