# De poort waar de Gateway op draait
server.port=8080

# Routing configuratie
spring.cloud.gateway.routes[0].id=ordering-service
spring.cloud.gateway.routes[0].uri=http://localhost:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/orders/**

spring.cloud.gateway.routes[1].id=payment-service
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/payments/**
spring.main.web-application-type=reactive